
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action EditionAction;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Button Visualización;
	
	private global::Gtk.Button salir;
	
	private global::Gtk.VBox vbox2;
	
	private global::Gtk.Label label1;
	
	private global::Gtk.HBox hbox4;
	
	private global::Gtk.ToggleButton Auto;
	
	private global::Gtk.ComboBox speed;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.EditionAction = new global::Gtk.Action ("EditionAction", global::Mono.Unix.Catalog.GetString ("Edition"), null, null);
		this.EditionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edition");
		w1.Add (this.EditionAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 129;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		this.vbox1.BorderWidth = ((uint)(9));
		// Container child vbox1.Gtk.Box+BoxChild
		this.Visualización = new global::Gtk.Button ();
		this.Visualización.CanFocus = true;
		this.Visualización.Name = "Visualización";
		this.Visualización.UseUnderline = true;
		this.Visualización.Label = global::Mono.Unix.Catalog.GetString ("Visualización");
		this.vbox1.Add (this.Visualización);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.Visualización]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.salir = new global::Gtk.Button ();
		this.salir.CanFocus = true;
		this.salir.Name = "salir";
		this.salir.UseUnderline = true;
		this.salir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
		this.vbox1.Add (this.salir);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.salir]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.hpaned1.Add (this.vbox1);
		global::Gtk.Paned.PanedChild w4 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox1]));
		w4.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		this.vbox2.BorderWidth = ((uint)(15));
		// Container child vbox2.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Cuadro de Mando - Actuadores");
		this.vbox2.Add (this.label1);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
		w5.Position = 0;
		w5.Expand = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		this.hbox4.BorderWidth = ((uint)(42));
		// Container child hbox4.Gtk.Box+BoxChild
		this.Auto = new global::Gtk.ToggleButton ();
		this.Auto.CanFocus = true;
		this.Auto.Name = "Auto";
		this.Auto.UseUnderline = true;
		this.Auto.BorderWidth = ((uint)(4));
		this.Auto.Label = global::Mono.Unix.Catalog.GetString ("Auto: OFF");
		this.hbox4.Add (this.Auto);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.Auto]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.speed = global::Gtk.ComboBox.NewText ();
		this.speed.AppendText (global::Mono.Unix.Catalog.GetString ("speed0"));
		this.speed.AppendText (global::Mono.Unix.Catalog.GetString ("speed1"));
		this.speed.AppendText (global::Mono.Unix.Catalog.GetString ("speed2"));
		this.speed.Name = "speed";
		this.speed.Active = 0;
		this.speed.AddTearoffs = true;
		this.hbox4.Add (this.speed);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.speed]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox2.Add (this.hbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
		w8.Position = 1;
		w8.Fill = false;
		this.hpaned1.Add (this.vbox2);
		this.Add (this.hpaned1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 602;
		this.DefaultHeight = 279;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.Visualización.Clicked += new global::System.EventHandler (this.muestraVisualizacion);
		this.salir.Clicked += new global::System.EventHandler (this.exit);
		this.Auto.Pressed += new global::System.EventHandler (this.estadoAuto);
		this.speed.Changed += new global::System.EventHandler (this.cambiaVelocidad);
	}
}
